Just domo
big-squid/perhap_api pull request #3
Opened 2017-07-17 22:07 UTC by selenarakowski

3rd time is a charm..... maybe?

2017-07-18 14:01 UTC, randysecrist requested changes

2017-07-18 14:01 UTC, randysecrist commented on apps/reducers/lib/services/domoget.ex
> +  def merge_three_stores(dataset, _type, store_1, store_2, store_3) when is_list(dataset) do
Could merge two & three stores be generically changed to just be "merge_stores"?

(When merging three stores (A,B, and C), could we make it simply two operations of merge stores?

e.g.
X = merge(A,B)
Y = merge(X, C)

2017-07-18 14:01 UTC, randysecrist commented on apps/reducers/lib/services/stats.ex
> +    # apply(__MODULE__, type, [model, preped_data])
Comments still needed?

2017-07-18 14:01 UTC, randysecrist commented on apps/reducers/lib/services/domoget.ex
> +  def date(datestring) when datestring == "", do: 1494287000000 #this date will be before season1 starts, so it won't get played
May want to comment what the job of the date function is.  I can see the pattern match on a specific date which represents tournament start time.

But when looking at just this set of functions by itself, I can't really tell what should be happening.

Any idea how much test coverage (% lines covered) the domoget module has?

2017-07-18 14:01 UTC, randysecrist commented on apps/api/mix.exs
> +      {:gen_stage, "~> 0.12.1"},
Thank you for updating this.

2017-07-18 14:01 UTC, randysecrist commented on apps/reducers/lib/mix/tasks/bracket.ex
> +        {score, accuracy} = total_week(decoded_data[week])
Does the bracket task need to be run on next deploy?  Any others?

2017-07-18 15:29 UTC, selenarakowski commented on apps/reducers/lib/mix/tasks/bracket.ex
> +        {score, accuracy} = total_week(decoded_data[week])
no it doesn't, well it runs on a cron every sunday.

2017-07-18 15:30 UTC, selenarakowski commented on apps/api/mix.exs
> +      {:gen_stage, "~> 0.12.1"},
you're welcome

2017-07-18 15:30 UTC, selenarakowski commented on apps/reducers/lib/services/stats.ex
> +    # apply(__MODULE__, type, [model, preped_data])
no, when moving things around I wanted to make sure i kept what was needed, obviously that isn't.

2017-07-18 15:39 UTC, selenarakowski commented on apps/reducers/lib/services/domoget.ex
> +  def date(datestring) when datestring == "", do: 1494287000000 #this date will be before season1 starts, so it won't get played
added some comments there!

2017-07-19 17:39 UTC, randysecrist approved these changes

2017-07-19 17:39 UTC, merged